[ -z "$PS1" ] && return

export HISTCONTROL=ignoreboth:erasedups
export HISTSIZE=1000
export HISTFILESIZE=2000
shopt -s histappend
shopt -s checkwinsize
#shopt -s globstar

if [ -f ~/.bash_aliases ]; then
  . ~/.bash_aliases
fi
